const fs = require('fs');

// 1. Pehle purani file ko safely read karne ki koshish karte hain
let rawData = fs.readFileSync('data/actors.json', 'utf8');

// Purane data se bad control characters (jaise \n ya \r strings ke andar) ko saaf karna
// Yeh regex hidden characters ko remove kar dega jo JSON.parse ko disturb karte hain
const cleanData = rawData.replace(/[\u0000-\u001F\u007F-\u009F]/g, "");

let data = [];
try {
    data = JSON.parse(cleanData);
} catch (e) {
    console.log("Purani file mein masla tha, empty array se start kar rahe hain.");
    data = [];
}

const batch7Actors = [
  {
    "id": 510,
    "name": "Al Pacino",
    "fullName": "Alfredo James Pacino",
    "slug": "al-pacino",
    "country": "United States",
    "countrySlug": "united-states",
    "born": "April 25, 1940",
    "birthPlace": "New York City, New York",
    "nationality": "American",
    "profession": ["Actor", "Director"],
    "genre": ["Crime", "Drama"],
    "bio": "Considered one of the greatest actors of all time, famous for his roles in The Godfather and Scarface.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Al_Pacino",
    "movies": ["The Godfather", "Scarface", "Scent of a Woman", "The Irishman"],
    "dramas": ["Hunters"],
    "costars": ["Robert De Niro"],
    "awards": ["1 Academy Award", "2 Tonys", "2 Emmys", "4 Golden Globes"],
    "active": "1967-present",
    "netWorth": "$120 Million",
    "spouse": "None",
    "children": "4"
  },
  {
    "id": 511,
    "name": "Robert De Niro",
    "fullName": "Robert Anthony De Niro Jr.",
    "slug": "robert-de-niro",
    "country": "United States",
    "countrySlug": "united-states",
    "born": "August 17, 1943",
    "birthPlace": "New York City, New York",
    "nationality": "American-Italian",
    "profession": ["Actor", "Producer"],
    "genre": ["Crime", "Drama", "Comedy"],
    "bio": "Known for his long-standing collaboration with Martin Scorsese and his intense method acting.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Robert_De_Niro",
    "movies": ["Taxi Driver", "Raging Bull", "The Irishman", "Goodfellas"],
    "dramas": [],
    "costars": ["Al Pacino", "Joe Pesci"],
    "awards": ["2 Academy Awards", "1 Golden Globe"],
    "active": "1963-present",
    "netWorth": "$500 Million",
    "spouse": "Grace Hightower (Ex)",
    "children": "7"
  },
  {
    "id": 512,
    "name": "Florence Pugh",
    "fullName": "Florence Pugh",
    "slug": "florence-pugh",
    "country": "United Kingdom",
    "countrySlug": "united-kingdom",
    "born": "January 3, 1996",
    "birthPlace": "Oxford, England",
    "nationality": "British",
    "profession": ["Actress"],
    "genre": ["Drama", "Sci-Fi", "Action"],
    "bio": "Gained international recognition for her roles in Midsommar and Little Women, now a major part of the MCU.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Florence_Pugh",
    "movies": ["Little Women", "Black Widow", "Oppenheimer", "Dune: Part Two"],
    "dramas": ["Hawkeye"],
    "costars": ["Scarlett Johansson", "Timothée Chalamet"],
    "awards": [],
    "active": "2014-present",
    "netWorth": "$8 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 513,
    "name": "Zendaya",
    "fullName": "Zendaya Maree Stoermer Coleman",
    "slug": "zendaya",
    "country": "United States",
    "countrySlug": "united-states",
    "born": "September 1, 1996",
    "birthPlace": "Oakland, California",
    "nationality": "American",
    "profession": ["Actress", "Singer"],
    "genre": ["Drama", "Sci-Fi"],
    "bio": "The youngest two-time Emmy winner for Lead Actress, known for Euphoria and the Spider-Man series.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Zendaya",
    "movies": ["Spider-Man: No Way Home", "Dune", "Challengers"],
    "dramas": ["Euphoria"],
    "costars": ["Tom Holland", "Timothée Chalamet"],
    "awards": ["2 Emmys", "1 Golden Globe"],
    "active": "2009-present",
    "netWorth": "$22 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 514,
    "name": "Colin Farrell",
    "fullName": "Colin James Farrell",
    "slug": "colin-farrell",
    "country": "Ireland",
    "countrySlug": "ireland",
    "born": "May 31, 1976",
    "birthPlace": "Castleknock, Ireland",
    "nationality": "Irish",
    "profession": ["Actor"],
    "genre": ["Drama", "Crime", "Action"],
    "bio": "A versatile Irish actor known for both blockbusters and acclaimed independent films.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Colin_Farrell",
    "movies": ["The Banshees of Inisherin", "The Batman", "In Bruges"],
    "dramas": ["The Penguin", "True Detective"],
    "costars": ["Brendan Gleeson"],
    "awards": ["2 Golden Globes"],
    "active": "1997-present",
    "netWorth": "$80 Million",
    "spouse": "None",
    "children": "2"
  },
  {
    "id": 515,
    "name": "Brendan Gleeson",
    "fullName": "Brendan Gleeson",
    "slug": "brendan-gleeson",
    "country": "Ireland",
    "countrySlug": "ireland",
    "born": "March 29, 1955",
    "birthPlace": "Dublin, Ireland",
    "nationality": "Irish",
    "profession": ["Actor", "Director"],
    "genre": ["Drama", "Comedy", "Fantasy"],
    "bio": "Famous for his role as Mad-Eye Moody in Harry Potter and his collaborations with Colin Farrell.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Brendan_Gleeson",
    "movies": ["Braveheart", "In Bruges", "Harry Potter", "The Banshees of Inisherin"],
    "dramas": ["The Comey Rule"],
    "costars": ["Colin Farrell"],
    "awards": ["1 Emmy"],
    "active": "1989-present",
    "netWorth": "$4 Million",
    "spouse": "Mary Gleeson",
    "children": "4"
  },
  {
    "id": 516,
    "name": "Michelle Williams",
    "fullName": "Michelle Ingrid Williams",
    "slug": "michelle-williams",
    "country": "United States",
    "countrySlug": "united-states",
    "born": "September 9, 1980",
    "birthPlace": "Kalispell, Montana",
    "nationality": "American",
    "profession": ["Actress"],
    "genre": ["Drama", "Romance"],
    "bio": "Known for her work in small-scale independent films with dark or tragic themes.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Michelle_Williams_(actress)",
    "movies": ["Brokeback Mountain", "Blue Valentine", "The Fabelmans"],
    "dramas": ["Dawson's Creek", "Fosse/Verdon"],
    "costars": ["Ryan Gosling"],
    "awards": ["2 Golden Globes", "1 Emmy"],
    "active": "1993-present",
    "netWorth": "$30 Million",
    "spouse": "Thomas Kail",
    "children": "3"
  },
  {
    "id": 517,
    "name": "Eiza Gonzalez",
    "fullName": "Eiza Gonzalez Reyna",
    "slug": "eiza-gonzalez",
    "country": "Mexico",
    "countrySlug": "mexico",
    "born": "January 30, 1990",
    "birthPlace": "Mexico City, Mexico",
    "nationality": "Mexican",
    "profession": ["Actress", "Singer"],
    "genre": ["Action", "Sci-Fi"],
    "bio": "Rose to prominence in Mexican telenovelas before successfully transitioning to Hollywood action films.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Eiza_Gonz%C3%A1lez",
    "movies": ["Baby Driver", "Godzilla vs. Kong", "Ambulance"],
    "dramas": ["3 Body Problem"],
    "costars": ["Ansel Elgort"],
    "awards": [],
    "active": "2007-present",
    "netWorth": "$5 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 518,
    "name": "Aaron Taylor-Johnson",
    "fullName": "Aaron Perry Taylor-Johnson",
    "slug": "aaron-taylor-johnson",
    "country": "United Kingdom",
    "countrySlug": "united-kingdom",
    "born": "June 13, 1990",
    "birthPlace": "High Wycombe, England",
    "nationality": "British",
    "profession": ["Actor"],
    "genre": ["Action", "Drama"],
    "bio": "Known for Kick-Ass and playing Quicksilver in the MCU, often mentioned as a top contender for James Bond.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Aaron_Taylor-Johnson",
    "movies": ["Kick-Ass", "Nocturnal Animals", "Bullet Train", "Kraven the Hunter"],
    "dramas": [],
    "costars": ["Brad Pitt"],
    "awards": ["1 Golden Globe"],
    "active": "2001-present",
    "netWorth": "$16 Million",
    "spouse": "Sam Taylor-Johnson",
    "children": "4"
  },
  {
    "id": 519,
    "name": "Viggo Mortensen",
    "fullName": "Viggo Peter Mortensen Jr.",
    "slug": "viggo-mortensen",
    "country": "United States",
    "countrySlug": "united-states",
    "born": "October 20, 1958",
    "birthPlace": "New York City, New York",
    "nationality": "American-Danish",
    "profession": ["Actor", "Author", "Musician"],
    "genre": ["Fantasy", "Drama"],
    "bio": "Gained worldwide fame as Aragorn in The Lord of the Rings trilogy.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Viggo_Mortensen",
    "movies": ["The Lord of the Rings", "Green Book", "Eastern Promises"],
    "dramas": [],
    "costars": ["Mahershala Ali"],
    "awards": ["1 SAG Award"],
    "active": "1984-present",
    "netWorth": "$40 Million",
    "spouse": "Ariadna Gil (Partner)",
    "children": "1"
  },
  {
    "id": 520,
    "name": "Mahershala Ali",
    "fullName": "Mahershalalhashbaz Ali",
    "slug": "mahershala-ali",
    "country": "United States",
    "countrySlug": "united-states",
    "born": "February 16, 1974",
    "birthPlace": "Oakland, California",
    "nationality": "American",
    "profession": ["Actor"],
    "genre": ["Drama", "Sci-Fi"],
    "bio": "The first Muslim actor to win an Oscar, known for his calm and powerful screen presence.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Mahershala_Ali",
    "movies": ["Moonlight", "Green Book", "Leave the World Behind"],
    "dramas": ["True Detective", "House of Cards"],
    "costars": ["Viggo Mortensen"],
    "awards": ["2 Academy Awards", "1 Golden Globe", "1 Emmy"],
    "active": "2001-present",
    "netWorth": "$12 Million",
    "spouse": "Amatus Sami-Karim",
    "children": "1"
  },
  {
    "id": 521,
    "name": "Christian Slater",
    "fullName": "Christian Michael Leonard Slater",
    "slug": "christian-slater",
    "country": "United States",
    "countrySlug": "united-states",
    "born": "August 18, 1969",
    "birthPlace": "New York City, New York",
    "nationality": "American",
    "profession": ["Actor"],
    "genre": ["Drama", "Thriller", "Comedy"],
    "bio": "A major star of the late 80s and 90s, he found a career resurgence with the series Mr. Robot.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Christian_Slater",
    "movies": ["True Romance", "Heathers", "Interview with the Vampire"],
    "dramas": ["Mr. Robot", "Dr. Death"],
    "costars": ["Rami Malek"],
    "awards": ["1 Golden Globe"],
    "active": "1977-present",
    "netWorth": "$30 Million",
    "spouse": "Brittany Lopez",
    "children": "3"
  },
  {
    "id": 522,
    "name": "Rami Malek",
    "fullName": "Rami Said Malek",
    "slug": "rami-malek",
    "country": "United States",
    "countrySlug": "united-states",
    "born": "May 12, 1981",
    "birthPlace": "Los Angeles, California",
    "nationality": "American",
    "profession": ["Actor"],
    "genre": ["Drama", "Musical"],
    "bio": "Won an Oscar for his portrayal of Freddie Mercury and gained fame in the series Mr. Robot.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Rami_Malek",
    "movies": ["Bohemian Rhapsody", "No Time to Die", "Oppenheimer"],
    "dramas": ["Mr. Robot", "The Pacific"],
    "costars": ["Christian Slater"],
    "awards": ["1 Academy Award", "1 Golden Globe", "1 Emmy", "1 SAG Award"],
    "active": "2004-present",
    "netWorth": "$20 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 523,
    "name": "Stanley Tucci",
    "fullName": "Stanley Tucci Jr.",
    "slug": "stanley-tucci",
    "country": "United States",
    "countrySlug": "united-states",
    "born": "November 11, 1960",
    "birthPlace": "Peekskill, New York",
    "nationality": "American",
    "profession": ["Actor", "Director", "Cookbook Author"],
    "genre": ["Drama", "Comedy", "Sci-Fi"],
    "bio": "A beloved character actor and leading man known for his charm and culinary travel shows.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Stanley_Tucci",
    "movies": ["The Devil Wears Prada", "The Hunger Games", "The Lovely Bones"],
    "dramas": ["Citadel", "Feud"],
    "costars": ["Meryl Streep"],
    "awards": ["2 Golden Globes", "5 Emmys"],
    "active": "1982-present",
    "netWorth": "$25 Million",
    "spouse": "Felicity Blunt",
    "children": "5"
  },
  {
    "id": 524,
    "name": "Emily Blunt",
    "fullName": "Emily Olivia Laura Blunt",
    "slug": "emily-blunt",
    "country": "United Kingdom",
    "countrySlug": "united-kingdom",
    "born": "February 23, 1983",
    "birthPlace": "London, England",
    "nationality": "British-American",
    "profession": ["Actress"],
    "genre": ["Drama", "Action", "Sci-Fi"],
    "bio": "Known for her versatility, from comedies like The Devil Wears Prada to thrillers like A Quiet Place.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Emily_Blunt",
    "movies": ["A Quiet Place", "Oppenheimer", "Sicario", "The Devil Wears Prada"],
    "dramas": ["The English"],
    "costars": ["Cillian Murphy", "John Krasinski"],
    "awards": ["1 Golden Globe", "1 SAG Award"],
    "active": "2001-present",
    "netWorth": "$80 Million",
    "spouse": "John Krasinski",
    "children": "2"
  },
  {
    "id": 525,
    "name": "John Krasinski",
    "fullName": "John Burke Krasinski",
    "slug": "john-krasinski",
    "country": "United States",
    "countrySlug": "united-states",
    "born": "October 20, 1979",
    "birthPlace": "Newton, Massachusetts",
    "nationality": "American",
    "profession": ["Actor", "Director", "Producer"],
    "genre": ["Comedy", "Action", "Horror"],
    "bio": "Became famous as Jim Halpert on The Office before becoming a successful director and action star.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/John_Krasinski",
    "movies": ["A Quiet Place", "13 Hours", "IF"],
    "dramas": ["The Office", "Jack Ryan"],
    "costars": ["Emily Blunt"],
    "awards": ["2 SAG Awards"],
    "active": "2000-present",
    "netWorth": "$80 Million",
    "spouse": "Emily Blunt",
    "children": "2"
  },
  {
    "id": 526,
    "name": "Nicolas Cage",
    "fullName": "Nicolas Kim Coppola",
    "slug": "nicolas-cage",
    "country": "United States",
    "countrySlug": "united-states",
    "born": "January 7, 1964",
    "birthPlace": "Long Beach, California",
    "nationality": "American",
    "profession": ["Actor", "Producer"],
    "genre": ["Action", "Drama", "Fantasy"],
    "bio": "Known for his highly expressive and unique acting style, starring in both blockbusters and cult films.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Nicolas_Cage",
    "movies": ["National Treasure", "Leaving Las Vegas", "Face/Off", "Longlegs"],
    "dramas": [],
    "costars": ["John Travolta"],
    "awards": ["1 Academy Award", "1 Golden Globe", "1 SAG Award"],
    "active": "1981-present",
    "netWorth": "$25 Million",
    "spouse": "Riko Shibata",
    "children": "3"
  },
  {
    "id": 527,
    "name": "John Travolta",
    "fullName": "John Joseph Travolta",
    "slug": "john-travolta",
    "country": "United States",
    "countrySlug": "united-states",
    "born": "February 18, 1954",
    "birthPlace": "Englewood, New Jersey",
    "nationality": "American",
    "profession": ["Actor", "Singer", "Pilot"],
    "genre": ["Musical", "Crime", "Action"],
    "bio": "Rose to fame in Grease and Saturday Night Fever before a career revival in Pulp Fiction.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/John_Travolta",
    "movies": ["Grease", "Pulp Fiction", "Face/Off", "Hairspray"],
    "dramas": ["The People v. O. J. Simpson"],
    "costars": ["Nicolas Cage", "Samuel L. Jackson"],
    "awards": ["1 Golden Globe", "1 Emmy"],
    "active": "1972-present",
    "netWorth": "$250 Million",
    "spouse": "Kelly Preston (Late)",
    "children": "3"
  },
  {
    "id": 528,
    "name": "Uma Thurman",
    "fullName": "Uma Karuna Thurman",
    "slug": "uma-thurman",
    "country": "United States",
    "countrySlug": "united-states",
    "born": "April 29, 1970",
    "birthPlace": "Boston, Massachusetts",
    "nationality": "American",
    "profession": ["Actress", "Model"],
    "genre": ["Action", "Crime", "Drama"],
    "bio": "The muse of Quentin Tarantino, famous for Pulp Fiction and the Kill Bill series.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Uma_Thurman",
    "movies": ["Pulp Fiction", "Kill Bill", "Batman & Robin"],
    "dramas": ["The Staircase"],
    "costars": ["Samuel L. Jackson", "Ethan Hawke"],
    "awards": ["1 Golden Globe"],
    "active": "1985-present",
    "netWorth": "$45 Million",
    "spouse": "Ethan Hawke (Ex)",
    "children": "3"
  },
  {
    "id": 529,
    "name": "Ethan Hawke",
    "fullName": "Ethan Green Hawke",
    "slug": "ethan-hawke",
    "country": "United States",
    "countrySlug": "united-states",
    "born": "November 6, 1970",
    "birthPlace": "Austin, Texas",
    "nationality": "American",
    "profession": ["Actor", "Director", "Author"],
    "genre": ["Drama", "Sci-Fi", "Horror"],
    "bio": "Known for the Before Trilogy and his career-spanning collaboration with Richard Linklater.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Ethan_Hawke",
    "movies": ["Training Day", "Before Sunrise", "Boyhood", "Gattaca"],
    "dramas": ["Moon Knight"],
    "costars": ["Uma Thurman", "Denzel Washington"],
    "awards": [],
    "active": "1985-present",
    "netWorth": "$55 Million",
    "spouse": "Ryan Shawhughes",
    "children": "4"
  }
];

const existing = new Set(data.map(a => a.slug));
const filtered = batch7Actors.filter(a => !existing.has(a.slug));
const merged = [...data, ...filtered];

// Dubara save karte waat hum JSON ko proper stringify karenge
fs.writeFileSync('data/actors.json', JSON.stringify(merged, null, 2), 'utf8');

console.log('Database cleaned and 20 new actors added successfully.');